#pragma config(Sensor, S1,     lightSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          motorS,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   DATALOG_SERIES_0    0

int lightVal = 0;

task main()
{

	int motorSpeed = 13; //13
	int column = 0;
	int motorPos = 0;
	int onButton;

	// Clear old data
  datalogClear();
	wait1Msec(2000);

	while(1){

		onButton = getTouchValue(touchSensor);
		displayTextLine(1, "%s,%d","green", onButton);


		if (onButton == 0){


			// datalogAddValue adds one row to the datalog but does not time stamp the value
   		datalogAddValue( DATALOG_SERIES_0, lightVal );


			setMotorSpeed(motorS, motorSpeed);
			motorPos = getMotorEncoder(motorS);
			lightVal = getColorReflected(lightSensor);}


		if (onButton == 1){
			playTone(1500, 60);
			wait1Msec(200);

			setMotorSpeed(motorS, -20);
			wait1Msec(1500);
			setMotorSpeed(motorS, 0);
			break;
		}
	}
}
